# Generated by Django 5.2 on 2025-08-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='urgency',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2),
        ),
    ]
